title: 'Bady "Terminator" Touray'
permalink: none
url: 'http://beta.abemedia.co.uk/badytouray'
timezone: Europe/London
exclude:
    - Gemfile
    - Gemfile.lock
analytics:
    provider: google_analytics
sharing:
    provider:
        - facebook
        - twitter
        - google
        - linkedin
        - pinterest
        - stumbleupon
    limit: '3'
profiles:
    provider:
        - facebook
        - twitter
        - google
    facebook: 'https://facebook.com/BadyTouray'
    twitter: 'https://twitter.com/BadyTouray'
    pinterest: 'https://pinterest.com/brightonjapan'
    google: 'https://plus.google.com/117487081810569331153'
defaults:
    -
        scope:
            path: ''
            type: posts
        values:
            layout: page
    -
        scope:
            path: ''
            type: pages
        values:
            layout: page
collections:
    content:
        output: true
        permalink: ':path.html'
facebook_gallery:
    exclude:
        - 'Timeline Photos'
        - 'Cover Photos'
        - 'Profile Pictures'
description: 'Bady "Terminator" Touray'
relative_permalinks: 'false'
recaptcha_public_key: 6Lf15v0SAAAAAMReHqDCinChFIhv-Ve66By0f90D
comments:
    provider: '1'
v: 6
baseurl: /
