title: 'Bady "Terminator" Touray'
permalink: none
url: 'http://badytouray.com'
timezone: Europe/London
exclude:
    - Gemfile
    - Gemfile.lock
analytics:
    provider: google_analytics
    tracking_id: UA-57584368-1
sharing:
    provider:
        - facebook
        - twitter
        - google
        - linkedin
        - pinterest
        - stumbleupon
    limit: '6'
    style: icons
profiles:
    provider:
        - facebook
        - twitter
        - google
        - instagram
    facebook: 'https://facebook.com/BadyTouray'
    twitter: 'https://twitter.com/BadyTouray'
    pinterest: 'https://pinterest.com/brightonjapan'
    google: 'https://plus.google.com/117487081810569331153'
    instagram: 'https://instagram.com/BadyTouray'
defaults:
    -
        scope:
            path: ''
            type: posts
        values:
            layout: post
    -
        scope:
            path: ''
            type: pages
        values:
            layout: page
    -
        scope:
            path: ''
            type: shop_categories
        values:
            layout: shop_category
    -
        scope:
            path: ''
            type: shop
        values:
            layout: shop_product
collections:
    fights:
        output: false
    videos:
        output: false
    content:
        output: true
        permalink: ':path.html'
    shop:
        output: true
        permalink: 'shop/:path.html'
    shop_categories:
        output: true
        permalink: 'shop/:path.html'
description: 'Bady "Terminator" Touray'
relative_permalinks: 'false'
recaptcha_public_key: 6Lf15v0SAAAAAMReHqDCinChFIhv-Ve66By0f90D
comments:
    provider: '1'
v: 16
baseurl: /
paypal: lil_blak@hotmail.co.uk
gems:
    - jekyll-sitemap
cdn: //cdn.abemedia.co.uk/0x0/badytouray/
