title: 'Brighton Japan Festival'
permalink: none
url: 'http://beta.abemedia.co.uk/badytouray'
timezone: Europe/London
exclude:
    - Gemfile
    - Gemfile.lock
analytics:
    provider: google_analytics
sharing:
    provider:
        - facebook
        - twitter
        - google
        - linkedin
        - pinterest
        - stumbleupon
    limit: '3'
profiles:
    provider:
        - facebook
        - twitter
    facebook: 'https://facebook.com/BadyTouray'
    twitter: 'https://twitter.com/BadyTouray'
    pinterest: 'https://pinterest.com/brightonjapan'
defaults:
    -
        scope:
            path: ''
            type: posts
        values:
            layout: page
    -
        scope:
            path: ''
            type: pages
        values:
            layout: page
    -
        scope:
            path: ''
            type: areas
        values:
            layout: area
    -
        scope:
            path: ''
            type: events
        values:
            layout: event
collections:
    content:
        title: Pages
        icon: sitemap
        output: true
        permalink: ':path.html'
    fights:
        title: Fights
        icon: trophy
        output: true
    videos:
        title: Videos
        icon: video-camera
        output: true
    sponsors:
        title: Sponsors
        icon: money
facebook_gallery:
    exclude:
        - 'Timeline Photos'
        - 'Cover Photos'
        - 'Profile Pictures'
        - Photos
description: 'Brighton Japan Festival '
relative_permalinks: 'false'
recaptcha_public_key: 6Lf15v0SAAAAAMReHqDCinChFIhv-Ve66By0f90D
comments:
    provider: '1'
v: 4a
baseurl: /
